[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = false
chain_id = 1284
auto_detect_solc = false
solc_version = "0.8.17"
evm_version = "london"
use_literal_content = true
bytecode_hash = "none"
optimizer = true
optimizer_runs = 200
libraries = []

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
