[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# auto_detect_remappings = false
# chain_id = 1280
# auto_detect_solc = false
solc_version = "0.8.21"
# evm_version = "london"
# use_literal_content = true
# bytecode_hash = "none"
# optimizer = true
# optimizer_runs = 200
# libraries = []

[rpc_endpoints]
# moonbase = "http://127.0.0.1:9944"
moonbase = "https://rpc.api.moonbase.moonbeam.network"
anvil = "http://127.0.0.1:8545"
# moonbase = "https://rpc.api.moonbase.moonbeam.network"
moonbeam = "https://rpc.api.moobeam.network"

[etherscan]
# moonbase = { key = "${MOONSCAN_API_KEY}" }
moonbeam = { key = "${MOONSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
