/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    CommerceContract: {
      address: "0x851356ae760d987E095750cCeb3bC6014560891C",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "encryptedAddress",
              type: "string",
            },
          ],
          name: "DeliveryAddressUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "listingID",
              type: "string",
            },
            {
              indexed: false,
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "DeliveryConfirmed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "listingID",
              type: "string",
            },
            {
              indexed: false,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint32",
              name: "price",
              type: "uint32",
            },
            {
              indexed: false,
              internalType: "uint32",
              name: "quantity",
              type: "uint32",
            },
          ],
          name: "ProductListed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "listingID",
              type: "string",
            },
            {
              indexed: false,
              internalType: "address",
              name: "buyer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint32",
              name: "quantity",
              type: "uint32",
            },
          ],
          name: "ProductPurchased",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_listingID",
              type: "string",
            },
          ],
          name: "confirmDelivery",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_title",
              type: "string",
            },
            {
              internalType: "string",
              name: "_description",
              type: "string",
            },
            {
              internalType: "uint32",
              name: "_price",
              type: "uint32",
            },
            {
              internalType: "uint32",
              name: "_quantity",
              type: "uint32",
            },
            {
              internalType: "string",
              name: "_formSelectionType",
              type: "string",
            },
            {
              internalType: "string",
              name: "_image",
              type: "string",
            },
            {
              internalType: "string",
              name: "_listingID",
              type: "string",
            },
          ],
          name: "createProduct",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "getDeliveryAddress",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getListingTitle",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "listingID",
              type: "string",
            },
          ],
          name: "getProductData",
          outputs: [
            {
              components: [
                {
                  internalType: "string",
                  name: "title",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "description",
                  type: "string",
                },
                {
                  internalType: "uint32",
                  name: "price",
                  type: "uint32",
                },
                {
                  internalType: "uint32",
                  name: "quantity",
                  type: "uint32",
                },
                {
                  internalType: "string",
                  name: "formSelectionType",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "image",
                  type: "string",
                },
                {
                  internalType: "address payable",
                  name: "creatorWallet",
                  type: "address",
                },
                {
                  internalType: "bool",
                  name: "isDelivered",
                  type: "bool",
                },
              ],
              internalType: "struct CommerceContract.ProductData",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          name: "products",
          outputs: [
            {
              internalType: "string",
              name: "title",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "uint32",
              name: "price",
              type: "uint32",
            },
            {
              internalType: "uint32",
              name: "quantity",
              type: "uint32",
            },
            {
              internalType: "string",
              name: "formSelectionType",
              type: "string",
            },
            {
              internalType: "string",
              name: "image",
              type: "string",
            },
            {
              internalType: "address payable",
              name: "creatorWallet",
              type: "address",
            },
            {
              internalType: "bool",
              name: "isDelivered",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_listingID",
              type: "string",
            },
            {
              internalType: "uint32",
              name: "_quantity",
              type: "uint32",
            },
          ],
          name: "purchaseProduct",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_deliveryAddress",
              type: "string",
            },
          ],
          name: "setDeliveryAddress",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_listingTitle",
              type: "string",
            },
          ],
          name: "setListingTitle",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    FrankContract: {
      address: "0x95401dc811bb5740090279Ba06cfA8fcF6113778",
      abi: [
        {
          inputs: [],
          name: "decrementCounter",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "getTotalCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "incrementCounter",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    ServiceContract: {
      address: "0xf5059a5D33d5853360D16C683c16e67980206f36",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "listingID",
              type: "string",
            },
            {
              indexed: false,
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "ServiceCompleted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "listingID",
              type: "string",
            },
            {
              indexed: false,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint32",
              name: "price",
              type: "uint32",
            },
            {
              indexed: false,
              internalType: "uint32",
              name: "quantity",
              type: "uint32",
            },
          ],
          name: "ServiceListed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "listingID",
              type: "string",
            },
            {
              indexed: false,
              internalType: "address",
              name: "buyer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint32",
              name: "quantity",
              type: "uint32",
            },
          ],
          name: "ServicePurchased",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_listingID",
              type: "string",
            },
          ],
          name: "confirmServiceCompletion",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_title",
              type: "string",
            },
            {
              internalType: "string",
              name: "_description",
              type: "string",
            },
            {
              internalType: "uint32",
              name: "_price",
              type: "uint32",
            },
            {
              internalType: "uint32",
              name: "_quantity",
              type: "uint32",
            },
            {
              internalType: "string",
              name: "_formSelectionType",
              type: "string",
            },
            {
              internalType: "string",
              name: "_image",
              type: "string",
            },
            {
              internalType: "string",
              name: "_listingID",
              type: "string",
            },
          ],
          name: "createService",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_listingID",
              type: "string",
            },
            {
              internalType: "uint32",
              name: "_quantity",
              type: "uint32",
            },
          ],
          name: "purchaseService",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          name: "services",
          outputs: [
            {
              internalType: "string",
              name: "title",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "uint32",
              name: "price",
              type: "uint32",
            },
            {
              internalType: "uint32",
              name: "quantity",
              type: "uint32",
            },
            {
              internalType: "string",
              name: "formSelectionType",
              type: "string",
            },
            {
              internalType: "string",
              name: "image",
              type: "string",
            },
            {
              internalType: "address payable",
              name: "creatorWallet",
              type: "address",
            },
            {
              internalType: "bool",
              name: "isCompleted",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
